services:
  db:
    image: mysql:8.0        # <-- version stable
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: collecte
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  dbdata:
